### ISSUE TITLE
Note scrolls up to the first line (Android Studio)

### ISSUE THREAD

**Issue by taurelas** [jrana/quicknotes#10]
Note jumps back up to the first line when regaining focus.

To test:
1. Write a note that exceeds the amount of displayed lines.
2. Click anywhere outside the note
3. Click back on the note.

This is especially annoying when you have several pages of text and click to, say, turn down the volume.

**Comment by kmccullough** [comment]
I have the same issue on Mac Sierra. I agree, this is pretty infuriating. Trying to take some notes on a new project I've been introduced to, but when I change the file in the editor, and then click back to the notes pane to append or insert notes at the insertion point down the page, it jumps back to the top and I have to search for where I was all over again.

**Comment by crash83k** [comment]
Yeah, I'm having this issue with it too, in PhpStorm/WebStorm. Otherwise, it's a really nice plugin.

**Comment by jrana** [comment]
Fixed in version 3. Now remembers the caret position on focus.
