### ISSUE TITLE
Search is case sensitive by default (Android Studio)

### ISSUE THREAD

**Issue by taurelas** [jrana/quicknotes#12]
Search is case sensitive by default.

I may be wrong but the convention appears to be that:
i) if search phrase is all lower case -> search is case insensitive
ii) if search phrase has some capital letters (i.e. the user actually bothered to press the shift key) -> case sensitive

**Comment by kmccullough** [comment]
I am using Mac Sierra. My testing has shown that case is always sensitive. However, the search feature does not search titles of notes, only text within notes. @taurelas Could that have been what you experienced? In my opinion, case should always be insensitive unless you explicitly add a checkbox to force match case. Regex would also be nice to have.

**Comment by jrana** [comment]
Fixed in upcoming release 2.9.6
