### ISSUE TITLE
Dark theme - images are not consistent

### ISSUE THREAD

**Issue by PixelT** [jrana/quicknotes#2]
As in title:

![options bar](https://image.prntscr.com/image/CDY6YZxtRga4NcdM-GSn0Q.png)

**Comment by Dgc2002** [comment]
To add to this the input fields in the options dialog suffer from this as well:  
  
![image](https://user-images.githubusercontent.com/3957791/27235903-54f3e824-5288-11e7-8d9c-4072084d3fd3.png)

**Comment by grexe** [comment]
I really like the plugin and need such a feature, but the colors are really distracting and the plugin feels quite out of place in newer IntelliJ versions, esp. with Darcula theme, but also the strange toggle buttons look very inconsistent and don't fit in the simple, elegant IntelliJ design.
Please make the plugin and its dialog use standard IntelliJ theme and controls.

**Comment by jrana** [comment]
Fixed in 2.9.6. Now plugin is more IDEA theme aware.
![quick notes options dialog](https://user-images.githubusercontent.com/6390918/34459380-71323dd0-edbd-11e7-9b27-e965fbe79d82.png)

**Comment by jrana** [comment]
![quick notes toolbar](https://user-images.githubusercontent.com/6390918/34459387-9c97f672-edbd-11e7-9fd7-0270402597bf.png)
