### ISSUE TITLE
PHPSTORM 2018.2 + display problem 

### ISSUE THREAD

**Issue by alfiqmiq** [jrana/quicknotes#22]
After latest upgrade (to phstorm 2018.2) when note (or list of notes) are long and scrollbar appears, display box with notes is divided  (half is simple gray and display nothing)

![image](https://user-images.githubusercontent.com/9507245/43430908-965a6466-946b-11e8-9851-f5bab70bc661.png)

**Comment by LaughDonor** [comment]
Also occurs in Datagrip 2.2 and PyCharm. I assume it's across all IDEs.

**Comment by loveorigami** [comment]
+ 1

**Comment by alfiqmiq** [comment]
PHPStorm support says that they do some changes in PHPstorm, and author of quick notes plugin should fix it to work properly

**Comment by LaughDonor** [comment]
@alfiqmiq , it happens in other IDEs as well, not just PHPStorm

**Comment by alfiqmiq** [comment]
I'm using PHPStorm so I wrote about my issue.

**Comment by nymo** [comment]
Same problem here in PHPStorm 2018.2

**Comment by knezmilos13** [comment]
Same problem in Android Studio 3.1.4 and PHPStorm 2017.3 and 2018.2

**Comment by jrana** [comment]
Seems a weird issue, looking into it.

**Comment by jrana** [comment]
Fixed in version 3.2 !!!
