### ISSUE TITLE
Is it possible to use IntelliJ's 'Color Picker'

### ISSUE THREAD

**Issue by Dgc2002** [jrana/quicknotes#3]
The current color configuration provided by the plugin is a bit lacking in my opinion. Tabs aren't remembered after choosing a color, so if you're working in the RGB tab and want to keep tweaking it the dialog opens to the Swatches tab anyways. There also isn't a color picker(something that allows you to choose a color currently on screen). I think the color configuration process would benefit greatly by using the dialog found in IntelliJ, seen here:  
  

![image](https://user-images.githubusercontent.com/3957791/27235705-722bce9e-5287-11e7-9779-4f72ee233f1b.png)
  
Using the color picker:  
![image](https://user-images.githubusercontent.com/3957791/27235794-d68d9a20-5287-11e7-87ef-afe8c1f04b3d.png)

**Comment by jrana** [comment]
Now using IntelliJ's 'Color Picker' in version 3.0
