### ISSUE TITLE
Separate line and line number coloring

### ISSUE THREAD

**Issue by Dgc2002** [jrana/quicknotes#4]
Currently the line number and line colors are tied to one another. I'd prefer if these were split into their own configurations as I might want softer lines but more pronounced numbers.   
  
Here's what it looks like when I try a softer line color:  

![image](https://user-images.githubusercontent.com/3957791/27235859-1ec9afb8-5288-11e7-8825-4c46cff68c08.png)

**Comment by jrana** [comment]
Done in 2.9.6
