### ISSUE TITLE
Update images on plugin page

### ISSUE THREAD

**Issue by Kendos-Kenlen** [jrana/quicknotes#5]
The images are really old, it would be better to have more up-to-date images and it would attract more users.

**Comment by jrana** [comment]
Thanks Kendos, yes the images really looks very old now :), will give the plugin a fresh look pretty soon.

**Comment by jrana** [comment]
Done. Coming up in 2.9.6.

![quick notes toolbar](https://user-images.githubusercontent.com/6390918/34459394-bda88dd6-edbd-11e7-81d8-0d2608fb96cd.png)
